# Generated by Django 5.2.4 on 2025-07-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_area_unit_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_aana',
            field=models.IntegerField(blank=True, help_text='Aana (आना)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_daam',
            field=models.IntegerField(blank=True, help_text='Daam (दाम)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_paisa',
            field=models.IntegerField(blank=True, help_text='Paisa (पैसा)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_ropani',
            field=models.IntegerField(blank=True, help_text='Ropani (रोपनी)', null=True),
        ),
    ]
