# Generated by Django 5.2.4 on 2025-07-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_property_area_alter_property_area_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google_maps_embed_url',
            field=models.TextField(blank=True, help_text='Google Maps embed URL or iframe code', null=True),
        ),
    ]
